#: import sm kivy.uix.screenmanager
#: import math math


<SaveDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"

        FileChooserIconView:
            id: filechooser

        TextInput:
            size_hint_y: None
            height: 30
            multiline: False
            text: root.file
            readonly: True

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, root.file)


<LegendClassContainer>:
    size_hint_y: None
    height: 30

    BoxLayout:
        size_hint: None, None
        size: 60, 30
        padding: 1
        canvas.before:
            Color:
                rgba: (0, 0, 0, 1)
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            canvas.before:
                Color:
                    rgba: root.cc_color
                Rectangle:
                    pos: self.pos
                    size: self.size

    Label:
        text: root.text_min
        color: (0,0,0,1)
        font_size: 14
        text_size: (self.width, self.height)
        halign: "right"
        valign: "middle"
        markup: True

    Label:
        size_hint_x: None
        width: 20
        text: "-"
        color: (0,0,0,1)
        font_size: 14

    Label:
        text: root.text_max
        color: (0,0,0,1)
        font_size: 14
        text_size: (self.width, self.height)
        halign: "left"
        valign: "middle"
        markup: True


<TH_Regions@Label>:
    size_hint_y: None
    height: 22
    canvas.before:
        Color:
            rgba: (0.32, 0.17, 0.22, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    text_size: (self.width-20, self.height)
    shorten: True
    halign: "right"
    valign: "middle"
    color: (1, 1, 1, 1)
    font_size: 14
    size_hint_x: None
    width: 198


<ThematicValues>:
    size_hint_y: None
    height: 22
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    color: (0, 0, 0, 1)
    font_size: 14
    size_hint_x: None
    width: 84
    markup: True


<TH_YearSelector@ToggleButton>:
    size_hint: (None, None)
    size: (50, 20)
    font_size: 12
    bold: True
    disabled_color: (1,1,1,1)
    background_disabled_down: './Sources/th_btn_years_down.png'
    disabled: True if self.state == "down" else False
    background_normal: './Sources/th_btn_years_normal.png'


<FormulaHintItem@BoxLayout>:
    size_hint_x: None
    width: 3
    canvas.before:
        Color:
            rgba: (0.96, 0.26, 0.21, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<FormulaHintLabel@Label>:
    size_hint_y: None
    markup: True
    italic: True
    font_size: 13
    text_size: (self.width-20, self.height-10)
    halign: "left"
    valign: "top"
    canvas.before:
        Color:
            rgba: (0.96, 0.96, 0.96, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<FunctionBtnBox@BoxLayout>:
    size_hint_y: None
    height: 40
    canvas.before:
        Color:
            rgba: (0.96, 0.96, 0.96, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<FunctionBtn@Button>:
    markup: True
    font_size: 13
    background_normal: './Sources/math_function_normal.png'
    background_down: './Sources/formula_item_down.png'
    text_size: (self.width-10, self.height)
    halign: "left"
    valign: "middle"


<FunctionBtnInfo@Button>:
    text: "?"
    size_hint: (None, None)
    size: (20, 20)
    font_size: 15
    background_normal: './Sources/math_function_normal.png'
    background_down: './Sources/formula_item_down.png'
    color: (0.2, 0.2, 0.2, 1)
    text_size: (self.width-10, self.height)
    halign: "center"
    valign: "middle"


<FunctionTypeLabel@Label>:
    size_hint_y: None
    height: 20
    color: (1,1,1,1)
    bold: True
    italic: True
    font_size: 13
    canvas.before:
        Color:
            rgba: (0.2, 0.2, 0.2, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<IRY_OptionBtn@Button>:
    size_hint_y: None
    height: 25
    background_normal: './Sources/iry_droplist_normal.png'
    background_down: './Sources/iry_droplist_normal.png'


<IRY_MainbuttonBtn@Button>:
    markup: True
    size_hint: (None, None)
    size: (90, 30)
    background_normal: './Sources/selected_iry_normal.png'
    background_down: './Sources/selected_iry_down.png'


<Calc_Formula_Item@Button>:
    size_hint: (None, None)
    height: 40
    width: self.texture_size[0] if self.text else 5
    font_size: 30
    border: (0, 0, 0, 0)
    background_normal: './Sources/formula_item_normal.png'
    background_down: './Sources/formula_item_normal.png'


<Calc_Func_Btn@Button>:
    size_hint: (None, None)
    size: (60, 35)
    background_normal: './Sources/func_calc_btn_normal.png'
    normal: './Sources/func_calc_btn_normal.png'
    background_down: './Sources/func_calc_btn_down.png'
    color: (0.3, 0.3, 0.3, 1) if self.state == 'normal' else (0, 0, 0, 1)


<Calc_Arith_Btn@Button>:
    size_hint: (None, None)
    size: (60, 35)
    background_normal: './Sources/arith_calc_btn_normal.png'
    normal: './Sources/arith_calc_btn_normal.png'
    background_down: './Sources/arith_calc_btn_down.png'
    color: (0.3, 0.3, 0.3, 1) if self.state == 'normal' else (0, 0, 0, 1)


<AllYearsLabel@Label>:
    text: "ALL"
    size_hint: (None, None)
    size: (25, 25)
    font_size: 11
    color: (0,0,0,1)
    canvas.before:
        Rectangle:
            source: './Sources/select_all_years_label.png'
            pos: self.pos
            size: self.size


<YearSelector@ToggleButton>:
    size_hint: (None, None)
    size: (75, 25)
    font_size: 12
    bold: True
    background_down: './Sources/btn_years_down.png'


<CountryScroll@ScrollView>:
    bar_width: 2
    bar_pos_x: "top"
    bar_margin: 5
    do_scroll_y: False
    bar_inactive_color: (0, 0, 0, 1)
    bar_color: (0.96, 0.26, 0.21, 1)


<CountryStack@StackLayout>:
    size_hint: (None, 1)
    width: self.minimum_width
    padding: (0, 10)
    orientation: "tb-lr"
    spacing: (20,0)


<CountryFrame@BoxLayout>:
    size_hint: (None, None)
    size: (200, 50)
    canvas.before:
        Color:
            rgba: (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<CountryBtnImage@Image>:
    size_hint: (None, None)
    size: (37, 50)
    source: './Sources/left_country_wdg.png'
    allow_stretch: False


<CountryMidFrame@BoxLayout>:
    orientation: "vertical"
    size_hint: (None, None)
    size: (113, 50)
    canvas:
        Rectangle:
            source: './Sources/center_country_wdg.png'
            pos: self.pos
            size: self.size


<CountryName@Label>:
    size_hint: (None, None)
    size: (113,30)
    text_size: (self.width, self.height)
    halign: "left"
    font_size: 14
    shorten: True


<CountryCode@Label>:
    size_hint: (None, None)
    size: (113,20)
    text_size: (self.width, self.height)
    halign: "left"
    valign: "top"
    font_size: 10
    bold: True
    color: (0.96, 0.26, 0.21, 1)


<CountrySelectToggle@ToggleButton>:
    color: (0,0,0,0)
    size_hint: (None, None)
    size: (50, 45)
    background_normal: './Sources/right_country_wdg_nonchecked.png'
    normal: './Sources/right_country_wdg_nonchecked.png'
    background_down: './Sources/right_country_wdg_checked.png'


<CountryMultiSelect@BoxLayout>:
    orientation: "vertical"
    size_hint: (None, None)
    size: (100, 50)
    canvas.before:
        Rectangle:
            source: './Sources/country_select_all.png'
            pos: self.pos
            size: self.size

    Label:
        text: "Select ALL"
        font_size: 14
        italic: True
        color: (0,0,0,1)
        text_size: (self.width, self.height)
        halign: "center"
        valign: "bottom"

    Label:
        text: "Deselect ALL"
        font_size: 14
        italic: True
        color: (0,0,0,1)
        text_size: (self.width, self.height)
        halign: "center"
        valign: "top"


<CountryBtn@Button>:
    italic: True
    size_hint: (None, None)
    size: (200, 30)
    font_size: 13
    color: (0,0,0,1)
    disabled_color: (1,1,1,1)
    background_normal: './Sources/region_groups_normal.png'
    background_down: './Sources/region_groups_down.png'
    background_disabled_normal: './Sources/region_groups_down.png'
    background_disabled_down: './Sources/region_groups_down.png'


<TempDataTable@GridLayout>:
    size_hint: (None, None)
    size: (self.minimum_width, self.minimum_height) if self.children else (0, 0)
    canvas.before:
        Color:
            rgba: (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    col_default_width: 100
    row_default_height: 20
    row_force_default: True
    padding: (1,1)
    spacing: 1


<DataViewOdd@Label>:
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    markup: True
    color: (0, 0, 0, 1)
    font_size: 14
    size_hint_x: None
    width: 100


<DataViewEven@Label>:
    canvas.before:
        Color:
            rgba: (1, 0.95, 0.95, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    markup: True
    color: (0, 0, 0, 1)
    font_size: 14
    size_hint_x: None
    width: 100


<DataViewTitle@Label>:
    canvas.before:
        Color:
            rgba: (0.96, 0.26, 0.21, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    text_size: (self.width-20, self.height)
    shorten: True
    halign: "right"
    color: (1, 1, 1, 1)
    font_size: 14
    size_hint_x: None
    width: 200
    bold: True


<HeadBox@BoxLayout>:
    canvas.before:
        Color:
            rgba: (0.96, 0.26, 0.21, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<YearHeader@Label>:
    size_hint: (None, None)
    size: (70, 20)
    text_size: (self.width-10, self.height)
    halign: "right"
    color: (1, 1, 1, 1)
    font_size: 14
    bold: True


<OrderBtn@Button>:
    size_hint: (None, None)
    size: (30, 8)
    border: (0, 0, 0, 0)

<XLine@BoxLayout>:
    size_hint_y: None
    height: 1
    canvas.after:
        Color:
            rgba: (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<YLine@BoxLayout>:
    size_hint_x: None
    width: 1
    canvas.after:
        Color:
            rgba: (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<RvwWidgetMainLayout@BoxLayout>:
    size_hint: (None, None)
    size: (300, 167)
    orientation: "vertical"
    padding: (19, 10, 19, 17)
    spacing: 7
    canvas:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            source: './Sources/indicators_widget.png'
            pos: self.pos
            size: self.size


<RvwWidgetScroll@ScrollView>:
    canvas.before:
        Color:
            rgba: (0.22, 0.22, 0.22, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    do_scroll_x: False
    bar_width: 2
    bar_inactive_color: (0.8, 0.8, 0.8, 1)
    bar_color: (0.96, 0.26, 0.21, 1)
    bar_margin: 3
    bar_pos_y: "right"


<RvwWidgetTitle@Label>:
    size_hint: (None, None)
    size: (212, self.texture_size[1])
    canvas.before:
        Color:
            rgba: (0, 1, 0, 0)
        Rectangle:
            pos: self.pos
            size: self.size
    padding_y: 8
    text_size: (self.width-16, None)
    italic: True
    font_size: 13


<RvwWidgetShortID@Label>:
    size_hint: (None, None)
    size: (50, 70)
    canvas.before:
        Color:
            rgba: (0.96, 0.26, 0.21, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    font_size: 30 if len(self.text) == 2 else 20


<RvwWidgetFootLayout@BoxLayout>:
    size_hint: (None, None)
    size: (262, 63)
    spacing: 1
    canvas:
        Color:
            rgba: (0.7, 0.7, 0.7, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<RvwWidgetCalc@BoxLayout>:
    size_hint: (None, None)
    height: 63
    orientation: "vertical"
    canvas:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<RvwWidgetCalcData@Label>:
    size_hint: (None, None)
    font_size: 20
    bold: True
    markup: True


<RvwWidgetCalcDesc@Label>:
    size_hint: (None, None)
    italic: True
    text_size: (self.width, self.height)
    halign: "center"
    valign: "bottom"
    font_size: 12
    color: (0.33, 0.33, 0.33, 1)


<RvwWidgetCalc2Desc@Label>:
    size_hint: (None, None)
    size: (45, 15)
    text_size: (self.width, self.height)
    halign: "right"
    valign: "middle"
    font_size: 11
    color: (0.33, 0.33, 0.33, 1)


<RvwWidgetCalc2Data@Label>:
    size_hint: (None, None)
    size: (45, 15)
    text_size: (self.width, self.height)
    halign: "left"
    valign: "middle"
    font_size: 14
    bold: True
    color: (0, 0.45, 0, 1)


<TopicTitle@Label>:
    canvas.before:
        Color:
            rgba: (0.16, 0.2, 0.24, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    size_hint: (1, None)
    height: 50+self.texture_size[1]
    color: (1, 1, 1, 1)
    bold: True
    font_size: 38
    text_size: (self.width-40, None)
    halign: 'center'


<TopicDescription@Label>:
    size_hint: (1, None)
    text_size: self.width-40, None
    height: 60+self.texture_size[1]
    color: (0, 0, 0, 1)
    italic: True
    font_size: 14


<TopicToggleButton>:
    size_hint: (1, None)
    height: 48
    background_normal: './Sources/button_normal.png'
    background_down: './Sources/button_down.png'
    bold: True
    font_size: 14


<IndexStackLayout>:
    size_hint: (1, None)
    padding: (7, 1, 1, 1)
    height: self.minimum_height


<IndexToggleButton>:
    canvas.before:
        Color:
            rgba: (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    color: (0, 0, 0, 1)
    font_size: 16
    size_hint: (None, None)
    text_size: (self.width-40, None)
    width: 380
    background_down: './Sources/grey_btn_down.png'


<MyIndexBox@BoxLayout>:
    orientation: "vertical"
    size_hint_y: None
    padding: (2, 0, 2, 2)
    canvas:
        Color:
            rgba: (0.18, 0.18, 0.18, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<BtnRmv>:
    size_hint: (None, None)
    height: 12
    width: 12
    border: (0, 0, 0, 0)
    background_down: './Sources/remove_normal.png'
    background_normal: './Sources/remove_down.png'


<ShadeLine@BoxLayout>:
    size_hint_y: None
    height: 1
    canvas.after:
        Color:
            rgba: (0.28, 0.58, 0.78, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<MyIndex@Label>:
    size_hint: (1, None)
    text_size: self.width-15, None
    height: 15 + self.texture_size[1]
    color: (1, 1, 1, 1)
    font_size: 14
    bold: True
    canvas.before:
        Color:
            rgba: (0.1, 0.3, 0.5, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<MyTopic@Label>:
    size_hint: (1, None)
    height: 10 + self.texture_size[1]
    color: (0.1, 0.3, 0.5, 1)
    font_size: 12
    bold: True
    italic: True
    text_size: self.width-20, None
    halign: 'right'
    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<SR_Title@Label>:
    size_hint_y: None
    height: 30
    text_size: (self.width, self.height)
    font_size: 14
    italic: True
    valign: "bottom"
    padding_x: 10


<SR_Clear@Button>:
    size_hint_y: None
    height: 25
    text: "Clear results (X)"
    italic: True
    font_size: 12
    color: (1, 1, 1, 1)
    background_normal: './Sources/clear_search.png'


<SR_Index@Label>:
    size_hint: (1, None)
    height: 15 + self.texture_size[1]
    color: (0, 0, 0, 1)
    font_size: 14
    text_size: self.width-15, None
    halign: 'left'
    markup: True
    canvas.before:
        Color:
            rgba: (0.9, 0.9, 0.9, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<SR_Topic@Label>:
    size_hint: (1, None)
    height: 10 + self.texture_size[1]
    color: (0, 0, 0, 1)
    font_size: 13
    bold: True
    text_size: self.width-20, None
    halign: 'left'
    canvas.before:
        Color:
            rgba: (0.75, 0.75, 0.75, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<SearchBox@BoxLayout>:
    orientation: "vertical"
    size_hint_y: None
    padding: (2, 2, 2, 2)
    canvas:
        Color:
            rgba: (0.18, 0.18, 0.18, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<SearchArea>:
    size_hint_y: None
    size_hint_x: None
    height: 40
    width: 103
    cursor_color: (0, 0, 0, 1)
    foreground_color: (0, 0, 0, 1)
    font_size: 13
    hint_text: " Search.."
    hint_text_color: (1, 1, 1, 1)
    padding: (4, 12, 4, 0)
    multiline: False
    background_normal: './Sources/search_background_normal_empty.png' if not bool(self.text) else './Sources/search_background_normal_filled.png'
    background_active: './Sources/search_background_active_empty.png' if not bool(self.text) else './Sources/search_background_active.png'


<AnimWidget@Widget>:
    canvas:
        Color:
            rgba: (0.34, 0.76, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    size_hint: (None, None)
    size: (100, 2)


<MainWindow>:
    core_build_progress_bar: core_build_progress_bar
    coredb_state: coredb_state
    index_selection: index_selection
    coredb_update_popup: coredb_update_popup.__self__

    orientation: "horizontal"

    CIMScreenManager:
        transition: sm.SwapTransition()

        id: manager
        Screen:
            name: 'Home'

            BoxLayout:
                padding: 10,0,0,0
                canvas.before:
                    Color:
                        rgba: (0.2, 0.2, 0.2, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                ScrollView:
                    do_scroll_x: False
                    bar_width: 5
                    bar_inactive_color: (1, 1, 1, 1)
                    bar_color: (0.34, 0.76, 1, 1)
                    bar_margin: 1
                    bar_pos_y: "right"
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    LabelTip:
                        size_hint: (None, None)
                        size: (self.texture_size[0]+40, self.texture_size[1]+40)
                        font_size: 15
                        markup: True
                        color: (0,0,0,1)

        IndexSelection:
            id: index_selection
            is_update_db: update_db
            is_manager: manager
            is_index_creation: index_creation
            ind_select_icon: ind_select_icon

        IndexCreation:
            id: index_creation
            ic_index_selection: index_selection
            ic_thematic_btn: thematic_btn
            ic_thematic_btn_box: thematic_btn_box
            ic_th_designer: th_designer

        MapDesigner:
            id: th_designer
            md_index_creation: index_creation

    BoxLayout:
        id: main_boxlayout
        orientation: "vertical"
        size_hint_x: None
        width: 100
        canvas.before:
            Color:
                rgba: (0.18, 0.18, 0.18, 1)
            Rectangle:
                pos: self.pos
                size: self.size


        Popup:
            id: coredb_update_popup
            size_hint: (None, None)
            height: 250
            width: 400
            title: "Update Indicator Database"
            on_parent: if self.parent == main_boxlayout: self.parent.remove_widget(self)

            BoxLayout:
                orientation: "vertical"

                Label:
                    id: coredb_state
                    size_hint_y: None
                    height: 80
                    text: "..."
                    text_size: (self.width, self.height)
                    halign: 'center'
                    valign: 'bottom'

                AnchorLayout:
                    id: core_build_progress_bar

                BoxLayout:
                    orientation: "horizontal"

                    Button:
                        disabled: root.processing
                        text: "Update"
                        on_release: root.threadonator(root.core_build)

                    Button:
                        text: "Return"
                        on_release:
                            coredb_update_popup.dismiss()
                            root.popup_active = False

        Label:
            size_hint: None, None
            size: 100, 30
            text: "MENU"
            font_size: 15
            text_size: (self.width, self.height)
            halign: 'center'
            valign: "bottom"
            bold: True

        AnchorLayout:
            anchor_x: "center"
            anchor_y: "top"

            BoxLayout:
                size_hint_y: None
                height: 370
                padding: 0, 5, 0, 5
                spacing: 40
                orientation: "vertical"

                BoxLayout:
                    size_hint_y: None
                    height:90
                    orientation: "vertical"

                    ToggleButton:
                        id: ind_select_icon
                        group: "menu"
                        size_hint: None, None
                        size: 100, 70
                        on_release:
                            if not root.processing: index_selection.build_indices()
                            else: self.state = "normal"
                        disabled: True if self.state == "down" else False
                        background_normal: './Sources/IndicatorSelection_inactive.png'
                        background_disabled_down: './Sources/IndicatorSelection_active.png'

                    Label:
                        size_hint: None, None
                        size: 100, 20
                        text: "Indicator Selection"
                        font_size: 11
                        text_size: (self.width, self.height)
                        halign: 'center'
                        valign: 'middle'

                BoxLayout:
                    size_hint_y: None
                    height:90
                    orientation: "vertical"

                    ToggleButton:
                        group: "menu"
                        size_hint: None, None
                        size: 100, 70
                        on_release:
                            if not root.processing: manager.current = 'IndexCreationScreen'
                            else: self.state = "normal"
                        disabled: True if self.state == "down" else False
                        background_normal: './Sources/IndexCreation_inactive.png'
                        background_disabled_down: './Sources/IndexCreation_active.png'

                    Label:
                        size_hint: None, None
                        size: 100, 20
                        text: "Index Creation"
                        font_size: 11
                        text_size: (self.width, self.height)
                        halign: 'center'
                        valign: 'middle'

                BoxLayout:
                    id: thematic_btn_box
                    opacity: 0
                    size_hint_y: None
                    height:100
                    orientation: "vertical"

                    ToggleButton:
                        id: thematic_btn
                        group: "menu"
                        size_hint: None, None
                        size: 0, 0
                        disabled: True if self.state == "down" else False
                        on_release: if thematic_btn.opacity == 1: manager.current = 'MapDesignerScreen'
                        background_normal: './Sources/ThematicMapper_inactive.png'
                        background_disabled_down: './Sources/ThematicMapper_active.png'

                    Label:
                        size_hint: None, None
                        size: 100, 20
                        text: "Thematic Mapper"
                        font_size: 11
                        text_size: (self.width, self.height)
                        halign: 'center'
                        valign: 'middle'

        Button:
            id: update_db
            size_hint: (None, None)
            height: 30
            width: 80
            pos_hint: {'center_x': 0.5}
            font_size: 14
            text: "Update DB"
            border: (0,0,0,0)
            bold: True
            italic: True
            text_size: (self.width, self.height)
            halign: 'center'
            valign: 'middle'
            on_release:
                root.popup_active = True
                root.threadonator(root.check)
                coredb_update_popup.__self__.open()

        ToggleButton:
            group: "menu"
            text: "?"
            font_size: 30
            italic: True
            bold: True
            size_hint: None, None
            size: 100, 50
            on_release: manager.current = 'Home'
            disabled: True if self.state == "down" else False
            disabled_color: (1,1,1,1)
            border: (0,0,0,0)
            background_normal: './Sources/transparent_frame.png'
            background_disabled_down: './Sources/transparent_frame.png'
            text_size: (self.width-20, self.height)
            halign: 'right'
            valign: 'bottom'

        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            height: 100
            padding: 11,0,11,0
            canvas.before:
                Color:
                    rgba: (1, 1, 1, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size

            Image:
                size_hint: (None, None)
                size: self.texture_size
                source: './Sources/CIM_logo.png'
                allow_stretch: False

            Label:
                size_hint_y: None
                height: 18
                font_size: 12
                bold: True
                text: "Ver. 1.0.1"
                color: (0.2, 0.2, 0.2, 1)


<IndexSelection>:
    topics_slider: topics_slider
    indices_slider: indices_slider
    topics_slider_box: topics_slider_box
    indices_slider_stack: indices_slider_stack
    index_desc_slider: index_desc_slider

    toggle_index_desc_container: toggle_index_desc_container
    toggle_index_desc_icon: toggle_index_desc_icon
    toggle_index_desc_label: toggle_index_desc_label

    add_index_container: add_index_container
    add_index_icon: add_index_icon
    add_index_label: add_index_label

    my_indicators_search_sm: my_indicators_search_sm
    my_indicators_slider: my_indicators_slider
    my_indicators_container: my_indicators_container
    search_results_slider: search_results_slider
    search_results_container: search_results_container

    search_area: search_area

    name: 'IndexSelectionScreen'
    BoxLayout:
        size_hint: (None, None)
        size: root.size
        canvas.before:
            Color:
                rgba: (1, 1, 1, 1)
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            orientation: "vertical"
            size_hint_x: None
            width: 305

            ScrollView:
                id: topics_slider
                do_scroll_x: False
                bar_width: 5
                bar_inactive_color: (0, 0, 0, 1)
                bar_color: (0.34, 0.76, 1, 1)

                BoxLayout:
                    id: topics_slider_box
                    size_hint_y: None
                    orientation: "vertical"
                    size_hint_x: None
                    width: 300
                    padding: (1, 1, 1, 1)
                    spacing: 1
                    canvas:
                        Color:
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

        BoxLayout:

            BoxLayout:
                orientation: "vertical"
                size_hint_x: None
                # 850 = 8(paddings) + 305(topics_slider) + 157(min width of my_indicators) + 380(min index slide)
                width: 0 if len(indices_slider_stack.children)==0 else 388+(abs(((root.width-850)//380)*380)+(((root.width-850)//380)*380))/2

                ScrollView:
                    id: indices_slider
                    do_scroll_x: False
                    bar_width: 5
                    bar_inactive_color: (0, 0, 0, 1)
                    bar_color: (0.34, 0.76, 1, 1)
                    bar_margin: 1
                    bar_pos_y: "left"
                    IndexStackLayout:
                        id: indices_slider_stack

                XLine:

                BoxLayout:
                    id: index_desc_box
                    canvas.before:
                        Color:
                            rgba: (0.18, 0.18, 0.18, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    orientation: "horizontal"
                    size_hint_y: None
                    height: 80

                    BoxLayout:
                        size_hint: (None, 1)
                        width: 15

                    AnchorLayout:
                        id: toggle_index_desc_container
                        size_hint: (None, 1)
                        anchor_x: "center"
                        anchor_y: "top"
                        width: 45

                        Button:
                            id: toggle_index_desc_icon
                            size_hint: (None, None)
                            width: 45
                            height: 17
                            background_down: './Sources/index_desc_up_down.png' if index_desc_box.height == 80 else './Sources/index_desc_down_down.png'
                            background_normal: './Sources/index_desc_up_normal.png' if index_desc_box.height == 80 else './Sources/index_desc_down_normal.png'
                            on_press:
                                if index_desc_box.height == 80: index_desc_box.height = 200
                                else: index_desc_box.height = 80

                        Label:
                            id: toggle_index_desc_label
                            size_hint: (1, None)
                            height: 50
                            text: "OPEN" if index_desc_box.height == 80 else "CLOSE"
                            color: (1, 1, 1, 1)
                            font_size: 12

                    ScrollView:
                        id: index_desc_slider
                        do_scroll_x: False
                        bar_width: 5
                        bar_inactive_color: (1, 1, 1, 1)
                        bar_color: (0.34, 0.76, 1, 1)
                        bar_margin: 1
                        bar_pos_y: "right"

                        Label:
                            text: "Select an Index to read the description.." if root.selected_indices["feat_index"] is None else root.selected_indices["feat_index"].note
                            text_size: (self.width-30, None)
                            size_hint_y: None
                            height: 30 + self.texture_size[1]
                            color: (1, 1, 1, 1)
                            font_size: 15

                    AnchorLayout:
                        id: add_index_container
                        size_hint_x: None

                        BoxLayout:
                            size_hint: (None, None)
                            height: add_index_icon.height + add_index_label.height
                            width: add_index_icon.width
                            orientation: "vertical"

                            Button:
                                id: add_index_icon
                                size_hint: (None, None)
                                width: 50
                                height: 35
                                background_normal: './Sources/btn_add_index_normal.png'
                                background_down: './Sources/btn_add_index_down.png'
                                on_press: root.on_my_indicators()

                            Label:
                                id: add_index_label
                                size_hint: (1, None)
                                height: 15
                                text: "ADD IND."
                                color: (1, 1, 1, 1)
                                font_size: 12

            BoxLayout:
                orientation: "horizontal"
                canvas:
                    Color:
                        rgba: (0.9, 0.9, 0.9, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                YLine:

                ScreenManager:
                    id: my_indicators_search_sm
                    transition: sm.FadeTransition(duration=0.1, clearcolor=(1,1,1,1))

                    Screen:
                        name: "search_index"

                        on_enter:
                            search_area.focus = True
                            search_results_slider.opacity = 1
                        on_pre_leave: search_results_slider.opacity = 0

                        BoxLayout:
                            orientation: "vertical"

                            BoxLayout:
                                id: child
                                canvas:
                                    Color:
                                        rgba: (33./255, 33./255, 33./255, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                orientation: "horizontal"
                                size_hint_y: None
                                height: 50

                                Image:
                                    size_hint_x: None
                                    width: 8
                                    source: './Sources/opened_tab1.png'
                                    allow_stretch: False

                                AnchorLayout:
                                    anchor_x: "left"

                                    SearchArea:
                                        id: search_area
                                        on_text: if len(self.text) > 2: root.search_results(self.text)

                                Image:
                                    size_hint_x: None
                                    width: 147
                                    source: './Sources/opened_tab2.png'
                                    allow_stretch: False

                            ScrollView:
                                id: search_results_slider
                                canvas.before:
                                    Color:
                                        rgba: (0.267, 0.259, 0.251, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                do_scroll_x: False
                                bar_width: 2
                                bar_inactive_color: (1, 1, 1, 1)
                                bar_color: (1, 1, 1, 1)
                                bar_margin: 2
                                bar_pos_y: "right"

                                GridLayout:
                                    id: search_results_container
                                    size_hint_y: None
                                    height: self.minimum_height
                                    cols: 1
                                    spacing: 10
                                    padding: (5, 10, 5, 10)

                            MyIndicesBar:
                                mib_my_indicators_search_sm: my_indicators_search_sm

                    Screen:
                        name: "my_indicators"

                        on_enter: my_indicators_slider.opacity = 1
                        on_pre_leave:
                            my_indicators_slider.opacity = 0
                            search_area.text = ""

                        BoxLayout:
                            orientation: "vertical"

                            SearchBar:
                                sb_my_indicators_search_sm: my_indicators_search_sm

                            BoxLayout:
                                canvas:
                                    Color:
                                        rgba: (0, 0, 0, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                size_hint_y: None
                                height: 2

                            BoxLayout:
                                canvas:
                                    Color:
                                        rgba: (33./255, 33./255, 33./255, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                                orientation: "horizontal"
                                size_hint_y: None
                                height: 50

                                Image:
                                    size_hint_x: None
                                    width: 8
                                    source: './Sources/opened_tab1.png'
                                    allow_stretch: False

                                AnchorLayout:
                                    anchor_x: "left"

                                    Label:
                                        size_hint_y: None
                                        size_hint_x: None
                                        height: 50
                                        width: 8 + self.texture_size[0]
                                        text: "My Indicators"
                                        bold: True
                                        color: (1, 1, 1, 1)

                                Image:
                                    size_hint_x: None
                                    width: 147
                                    source: './Sources/opened_tab2.png'
                                    allow_stretch: False

                            ScrollView:
                                id: my_indicators_slider
                                do_scroll_x: False
                                bar_width: 3
                                bar_inactive_color: (0, 0, 0, 1)
                                bar_color: (0, 0, 0, 1)
                                bar_margin: 1
                                bar_pos_y: "right"

                                GridLayout:
                                    id: my_indicators_container
                                    size_hint_y: None
                                    height: self.minimum_height
                                    cols: 1
                                    spacing: 10
                                    padding: (5, 10, 5, 10)

                YLine:


# Closed and listening Bar
<MyIndicesBar>

    canvas.before:
        Color:
            rgba: (33./255, 33./255, 33./255, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    orientation: "horizontal"
    size_hint_y: None
    height: 50

    Image:
        size_hint_x: None
        width: 8
        source: './Sources/closed_tab1.png'
        allow_stretch: False

    AnchorLayout:
        anchor_x: "left"

        Label:
            size_hint_y: None
            size_hint_x: None
            height: 50
            width: 8 + self.texture_size[0]
            text: "My Indicators"
            bold: True
            color: (0.5, 0.5, 0.5, 1)

    Image:
        size_hint_x: None
        width: 147
        source: './Sources/closed_tab2.png'
        allow_stretch: False


# Closed and listening Bar
<SearchBar>

    canvas.before:
        Color:
            rgba: (33./255, 33./255, 33./255, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    orientation: "horizontal"
    size_hint_y: None
    height: 50

    Image:
        size_hint_x: None
        width: 8
        source: './Sources/closed_tab1.png'
        allow_stretch: False

    AnchorLayout:
        anchor_x: "left"

        TextInput:
            is_focusable: False
            readonly: True
            size_hint_y: None
            size_hint_x: None
            height: 40
            width: 103
            font_size: 13
            hint_text: " Search.."
            hint_text_color: (1, 1, 1, 1)
            padding: (4, 12, 4, 0)
            background_normal: './Sources/search_background_normal_empty.png'

    Image:
        size_hint_x: None
        width: 147
        source: './Sources/closed_tab2.png'
        allow_stretch: False


<IndexCreation>:
    btn_get_indicators: btn_get_indicators
    indicator_list: indicator_list
    downloading_state_icon: downloading_state_icon

    btn_view_indicators: btn_view_indicators
    btn_series_selection: btn_series_selection
    btn_index_algebra: btn_index_algebra

    toolbox_screenmanager: toolbox_screenmanager
    model_toolbox: model_toolbox

    screen_load_toolbox: screen_load_toolbox
    data_table_frame: data_table_frame
    data_table_top_slider: data_table_top_slider
    data_table_top: data_table_top
    data_table_img: data_table_img

    country_selection_sm: country_selection_sm
    years_stack: years_stack

    my_formula: my_formula
    calculator: calculator
    ind_calc_btn: ind_calc_btn
    indicator_var_builder: indicator_var_builder.__self__
    iry_table: iry_table
    iry_preview: iry_preview

    name: 'IndexCreationScreen'

    BoxLayout:
        orientation: "vertical"
        size_hint_x: None
        width: root.width-1

        XLine:

        BoxLayout:
            size_hint_y: None
            height: 100
            padding: (5, 5, 0, 5)
            canvas.before:
                Color:
                    rgba: (0.22, 0.22, 0.22, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                size_hint_x: None
                width: 130
                orientation: "vertical"

                ToggleButton:
                    id: btn_get_indicators
                    size_hint: (None, None)
                    width: 130
                    height: 68
                    background_normal: './Sources/get_indicators_btn_normal.png'
                    background_down: './Sources/get_indicators_btn_down.png'
                    background_disabled_down: './Sources/get_indicators_btn_down.png'
                    on_state: if self.state == "down": root.dl_manager()
                    on_disabled: if not self.disabled: root.ic_index_selection.dl_status_icon_setter()

                Label:
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 1) if not btn_get_indicators.disabled else (0.96, 0.26, 0.21, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    size_hint: (None, None)
                    size: (130, 22)
                    font_size: 13
                    color: (0.96, 0.26, 0.21, 1) if not btn_get_indicators.disabled else (1, 1, 1, 1)
                    text: "Get Indicator Data"

            RelativeLayout:
                size_hint: (None, None)

                Image:
                    size_hint: (None, None)
                    size: (41, 90)
                    source: './Sources/status_right_border.png'
                    allow_stretch: False

                Image:
                    id: downloading_state_icon
                    size_hint: (None, None)
                    size: (32, 90)
                    pos: (4, 0)
                    source: './Sources/status_error.png'
                    anim_delay: 0.15 if self.source == './Sources/loader.gif' else -1
                    allow_stretch: False


            BoxLayout:
                size_hint_x: None
                # 543 = sibling widths
                width: root.width - 543

            # Use that to add canvas color in the background. This will hide other buttons when overlapping them.
            BoxLayout:
                id: model_toolbox
                opacity: 0
                spacing: 5
                padding: (1, 0, 5, 0)
                canvas.before:
                    Color:
                        rgba: (0.22, 0.22, 0.22, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                BoxLayout:
                    size_hint_x: None
                    width: 130
                    orientation: "vertical"

                    Button:
                        id: btn_view_indicators
                        goto: "view_indicators_screen"
                        size_hint: (None, None)
                        width: 130
                        height: 68
                        background_normal: './Sources/view_indicators_btn_normal.png'
                        background_down: './Sources/view_indicators_btn_down.png'
                        background_disabled_down: './Sources/view_indicators_btn_down.png'
                        background_disabled_normal: './Sources/view_indicators_btn_down.png'
                        on_press:
                            root.toolbox_switcher(self)
                            root.init_data_viewer()

                    Label:
                        canvas.before:
                            Color:
                                rgba: (1, 1, 1, 1) if not btn_view_indicators.disabled else (0.96, 0.26, 0.21, 1)
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        size_hint: (None, None)
                        height: 22
                        width: 130
                        font_size: 13
                        color: (0.96, 0.26, 0.21, 1) if not btn_view_indicators.disabled else (1, 1, 1, 1)
                        text: "View Indicator Data"

                BoxLayout:
                    size_hint_x: None
                    width: 130
                    orientation: "vertical"

                    Button:
                        id: btn_series_selection
                        goto: "series_selection_screen"
                        size_hint: (None, None)
                        width: 130
                        height: 68
                        background_normal: './Sources/series_selection_btn_normal.png'
                        background_down: './Sources/series_selection_btn_down.png'
                        background_disabled_down: './Sources/series_selection_btn_down.png'
                        background_disabled_normal: './Sources/series_selection_btn_down.png'
                        on_press:
                            root.toolbox_switcher(self)
                            root.init_country_viewer("SSF")
                        on_state: if root.drawing_data: self.state = "normal"

                    Label:
                        canvas.before:
                            Color:
                                rgba: (1, 1, 1, 1) if not btn_series_selection.disabled else (0.96, 0.26, 0.21, 1)
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        size_hint: (None, None)
                        height: 22
                        width: 130
                        font_size: 13
                        color: (0.96, 0.26, 0.21, 1) if not btn_series_selection.disabled else (1, 1, 1, 1)
                        text: "Series Selection"

                BoxLayout:
                    size_hint_x: None
                    width: 130
                    orientation: "vertical"

                    Button:
                        id: btn_index_algebra
                        goto: "index_algebra_screen"
                        size_hint: (None, None)
                        width: 130
                        height: 68
                        background_normal: './Sources/index_algebra_btn_normal.png'
                        background_down: './Sources/index_algebra_btn_down.png'
                        background_disabled_down: './Sources/index_algebra_btn_down.png'
                        background_disabled_normal: './Sources/index_algebra_btn_down.png'
                        on_press:
                            if root.check_if_ry(): root.toolbox_switcher(self)
                            else: root.popuper("You must first select at least\none Region and one Year\nfrom Series Selection!", "Notice!")
                            if not my_formula.children: root.formula_spacer(0)
                        on_state: if root.drawing_data: self.state = "normal"

                    Label:
                        canvas.before:
                            Color:
                                rgba: (1, 1, 1, 1) if not btn_index_algebra.disabled else (0.96, 0.26, 0.21, 1)
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        size_hint: (None, None)
                        height: 22
                        width: 130
                        font_size: 13
                        color: (0.96, 0.26, 0.21, 1) if not btn_index_algebra.disabled else (1, 1, 1, 1)
                        text: "Index Algebra"

        XLine:

        BoxLayout:
            size_hint_y: None
            # 102 = above toolbar height
            height: root.height - 102
            canvas:
                Color:
                    rgba: (1, 1, 1, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: "vertical"
                size_hint_x: None
                width: 300
                canvas:
                    Color:
                        rgba: (0.9, 0.9, 0.9, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                BoxLayout:
                    opacity: 1 if not indicator_list.children else 0
                    orientation: "vertical"
                    padding: (0, 0, 0, (self.parent.height - 300))

                    Image:
                        size_hint: (None, None)
                        height: 128
                        width: 300
                        source: './Sources/Select_Indicators_First.png'
                        allow_stretch: False

                    Label:
                        size_hint: (None, None)
                        height: 60
                        width: 300
                        bold: True
                        font_size: 23
                        color: (1, 1, 1, 1)
                        text_size: (self.width, self.height)
                        halign: "center"
                        text: "Use button above\nto download your data.."

                ScrollView:
                    id: topics_slider
                    size_hint: (None, None)
                    size: (0, 0) if not indicator_list.children else (300, self.parent.height)
                    do_scroll_x: False
                    bar_width: 3
                    bar_margin: 2
                    bar_inactive_color: (0, 0, 0, 1)
                    bar_color: (0.96, 0.26, 0.21, 1)

                    BoxLayout:
                        id: indicator_list
                        size_hint: (None, None)
                        size: (0, 0) if not self.children else (300, 167*len(self.children))
                        orientation: "vertical"

            YLine:

            ScreenManager:
                id: toolbox_screenmanager
                transition: sm.SwapTransition(duration=0, clearcolor=(1,1,1,1))

                Screen:
                    id: screen_load_toolbox
                    name: "intro"
                    canvas.after:
                        Color:
                            rgba: (0.8, 0.8, 0.8, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                Screen:
                    name: "view_indicators_screen"
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    BoxLayout:
                        padding: (10, 10)

                        BoxLayout:
                            id: data_table_frame
                            orientation: "vertical"
                            padding: (1, 1)
                            canvas.before:
                                Color:
                                    rgba: (0, 0, 0, 1)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                            ScrollView:
                                id: data_table_top_slider
                                size_hint_y: None
                                height: data_table_top.height
                                bar_width: 2
                                bar_inactive_color: (0, 0, 0, 1)
                                bar_color: (0.96, 0.26, 0.21, 1)
                                do_scroll: (False, False)
                                scroll_x: data_table_slider.scroll_x
                                canvas.before:
                                    Color:
                                        rgba: (1, 1, 1, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                GridLayout:
                                    id: data_table_top
                                    size_hint: (None, None)
                                    size: (self.minimum_width, self.minimum_height)
                                    canvas.before:
                                        Color:
                                            rgba: (0, 0, 0, 1)
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size
                                    rows: 1
                                    col_default_width: 100
                                    row_default_height: 20
                                    row_force_default: True
                                    padding: (1,1)
                                    spacing: 1

                            ScrollView:
                                id: data_table_slider
                                bar_width: 2
                                bar_margin: -7
                                bar_pos_y: "right"
                                bar_inactive_color: (0, 0, 0, 1)
                                bar_color: (0.96, 0.26, 0.21, 1)
                                canvas.before:
                                    Color:
                                        rgba: (1, 1, 1, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                Image:
                                    id: data_table_img
                                    size_hint: (None, None)
                                    size: self.texture_size
                                    source: "./DB/table.png"
                                    allow_stretch: False

                    BoxLayout:
                        opacity: 1 if root.drawing_data else 0
                        orientation: "vertical"
                        canvas.before:
                            Color:
                                rgba: (1, 1, 1, 1)
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        BoxLayout:

                        BoxLayout:
                            size_hint: (None, None)
                            height: 2
                            width: int((float(toolbox_screenmanager.width)/float(100))*float(root.loading_percentage))
                            canvas.before:
                                Color:
                                    rgba: (0.96, 0.26, 0.21, 1)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                        AnchorLayout:
                            anchor_x:'center'
                            anchor_y:'top'

                            Label:
                                size_hint: (None, None)
                                size: self.texture_size
                                text: str(root.loading_percentage) + "%"
                                font_size: 22
                                color: (0.96, 0.26, 0.21, 1)
                                bold: True

                            Label:
                                text_size: (self.width-40, self.height-30)
                                text: "CREATING TABLE\nPlease Wait.."
                                font_size: 17
                                color: (0.22, 0.22, 0.22, 1)

                Screen:
                    name: "series_selection_screen"
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    BoxLayout:
                        orientation: "vertical"
                        padding: 10

                        BoxLayout:
                            size_hint_y: None
                            height: 61

                            ScrollView:
                                id: country_slider
                                size_hint_y: None
                                height: 61
                                bar_width: 2
                                bar_margin: -5
                                do_scroll_y: False
                                bar_inactive_color: (0, 0, 0, 1)
                                bar_color: (0.96, 0.26, 0.21, 1)

                                BoxLayout:
                                    size_hint: (None, None)
                                    # Child widths
                                    size: (813, 61)
                                    orientation: "vertical"
                                    padding: (5,0)
                                    spacing: 1

                                    BoxLayout:
                                        spacing: 1

                                        CountryBtn:
                                            text: "Sub-Saharan Africa"
                                            group: "SSF"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "SSF"

                                        CountryBtn:
                                            text: "Middle East & North Africa"
                                            group: "MEA"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "MEA"

                                        CountryBtn:
                                            text: "East Asia & Pacific"
                                            group: "EAS"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "EAS"

                                        CountryBtn:
                                            text: "South Asia"
                                            group: "SAS"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "SAS"

                                    BoxLayout:
                                        spacing: 1

                                        CountryBtn:
                                            text: "Europe & Central Asia"
                                            group: "ECS"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "ECS"

                                        CountryBtn:
                                            text: "North America"
                                            group: "NAC"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "NAC"

                                        CountryBtn:
                                            text: "Latin America & Caribbean"
                                            group: "LCN"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "LCN"

                                        CountryBtn:
                                            text: "Aggregates"
                                            group: "NA"
                                            disabled: True if country_selection_sm.current == self.group else False
                                            on_press: country_selection_sm.current = "NA"

                            BoxLayout:
                                size_hint_x: None
                                width: 3
                                canvas.before:
                                    Color:
                                        rgba: (0, 0, 0, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                            Label:
                                size_hint_x: None
                                width: 100
                                font_size: 15
                                text_size: (self.width-10, self.height-5)
                                halign: "left"
                                text: "REGIONS\nSELECTION"
                                color: (0,0,0,1)

                        BoxLayout:
                            size_hint_y: None
                            height: 5

                        ScreenManager:
                            id: country_selection_sm
                            transition: sm.FadeTransition(duration=0, clearcolor=(1,1,1,1))
                            canvas.before:
                                Color:
                                    rgba: (0.9, 0.9, 0.9, 1)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "SSF"

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "MEA"

                            Screen:
                                on_pre_enter:
                                    root.init_country_viewer(self.name)
                                name: "EAS"

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "SAS"

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "ECS"

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "NAC"

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "LCN"

                            Screen:
                                on_pre_enter: root.init_country_viewer(self.name)
                                name: "NA"

                        BoxLayout:
                            size_hint_y: None
                            height: 30

                        BoxLayout:
                            size_hint_y: None
                            height: year_scroll.height

                            BoxLayout:
                                id: year_scroll
                                size_hint: (None, None)
                                height: 120 + (toolbox_screenmanager.height - 6)% 50
                                width: years_stack.width + 2
                                padding: 1
                                canvas.before:
                                    Color:
                                        rgba: (0.22, 0.22, 0.22, 1)
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size

                                ScrollView:
                                    bar_width: 2
                                    bar_margin: -6
                                    bar_inactive_color: (0, 0, 0, 1)
                                    bar_color: (0.96, 0.26, 0.21, 1)
                                    canvas.before:
                                        Color:
                                            rgba: (1, 1, 1, 1)
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size

                                    GridLayout:
                                        id: years_stack
                                        cols: 10
                                        size_hint: (None, None)
                                        size: (self.minimum_width, self.minimum_height)
                                        padding: 10
                                        spacing: 5, 2

                            BoxLayout:
                                padding: (10, 0, 0, 0)

                                BoxLayout:
                                    size_hint_x: None
                                    width: 3
                                    canvas.before:
                                        Color:
                                            rgba: (0, 0, 0, 1)
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size

                                Label:
                                    size_hint_x: None
                                    width: 100
                                    font_size: 15
                                    text_size: (self.width-10, self.height-5)
                                    halign: "left"
                                    valign: "middle"
                                    text: "YEARS\nSELECTION"
                                    color: (0,0,0,1)

                Screen:
                    name: "index_algebra_screen"
                    on_pre_enter: root.init_iry_iteration()
                    canvas.before:
                        Color:
                            rgba: (1, 1, 1, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    BoxLayout:
                        orientation: 'vertical'
                        padding: 20

                        BoxLayout:
                            size_hint_y: None
                            height: 24

                            Image:
                                size_hint: (None, None)
                                size: (131, 24)
                                source: './Sources/ci_formula.png'
                                allow_stretch: False

                            Label:
                                size_hint_y: None
                                text_size: (self.width-100, self.height)
                                halign: "right"
                                valign: "bottom"
                                height: 30
                                font_size: 18
                                text: ">> Index Composer >>"
                                color: (0.1, 0.1, 0.1, 1)

                        BoxLayout:
                            size_hint_y: None
                            height: 5

                        BoxLayout:
                            size_hint_y: None
                            height: 1
                            canvas.before:
                                Color:
                                    rgba: (0.8, 0.8, 0.8, 1)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                        BoxLayout:
                            size_hint_y: None
                            height: 1

                        ScrollView:
                            do_scroll_x: False
                            bar_width: 5
                            bar_inactive_color: (1, 1, 1, 1)
                            bar_color: (0.34, 0.76, 1, 1)
                            bar_margin: 1
                            canvas.before:
                                Color:
                                    rgba: (0.95, 0.95, 0.95, 1)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                            StackLayout:
                                id: my_formula
                                size_hint_y: None
                                height: self.minimum_height

                        BoxLayout:
                            size_hint_y: None
                            height: 1

                        BoxLayout:
                            size_hint_y: None
                            height: 1
                            canvas.before:
                                Color:
                                    rgba: (0.8, 0.8, 0.8, 1)
                                Rectangle:
                                    pos: self.pos
                                    size: self.size

                        BoxLayout:
                            size_hint_y: None
                            height: 20

                        BoxLayout:
                            size_hint_y: None
                            height: 270
                            spacing: 120

                            BoxLayout:
                                size_hint: (None, None)
                                size: (422, 270)
                                padding: (10, 10, 10, 10)
                                spacing: 5
                                canvas:
                                    Color:
                                        rgba: (1, 1, 1, 1)
                                    Rectangle:
                                        source: './Sources/calculator_background.png'
                                        pos: self.pos
                                        size: self.size

                                BoxLayout:
                                    orientation: "vertical"
                                    size_hint: (None, None)
                                    size: (132, 250)

                                    BoxLayout:
                                        orientation: "vertical"
                                        size_hint: (None, None)
                                        size: (132, 55)
                                        padding: (0,0,0,3)

                                        Label:
                                            font_size: 17
                                            bold: True
                                            text_size: (self.width-10, self.height-5)
                                            halign: "left"
                                            valign: "middle"
                                            text: "Function Tools"
                                            color: (0,0,0,1)

                                        Button:
                                            size_hint: (None, None)
                                            size: (25, 25)
                                            text_size: (self.width, self.height+30)
                                            halign: "center"
                                            valign: "top"
                                            background_normal: './Sources/extra_calc_btn_normal.png'
                                            background_down: './Sources/extra_calc_btn_down.png'
                                            color: (0.2, 0.2, 0.2, 1)
                                            font_size: 30
                                            text: ','
                                            on_press: root.calc_btn_pressed(self.text)

                                    BoxLayout:
                                        size_hint: (None, None)
                                        size: (132, 195)
                                        padding: (1, 1)
                                        canvas.before:
                                            Color:
                                                rgba: (0.8, 0.8, 0.8, 1)
                                            Rectangle:
                                                pos: self.pos
                                                size: self.size

                                        ScrollView:
                                            size_hint: (None, None)
                                            size: (130, 193)
                                            bar_pos_y: "left"
                                            bar_width: 2
                                            bar_margin: -5
                                            bar_inactive_color: (0, 0, 0, 1)
                                            bar_color: (0.96, 0.26, 0.21, 1)

                                            GridLayout:
                                                cols: 1
                                                spacing: 1
                                                orientation: "vertical"
                                                size_hint_y: None
                                                height: self.minimum_height
                                                FunctionTypeLabel:
                                                    text: "Math"

                                                FunctionBtnBox:
                                                    function: ["fabs", str(math.fabs.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Absolute Value[/b][/color]\n[color=2b2b2b][size=11][i]fabs(x)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["log", str(math.log.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Logarithm[/b][/color]\n[color=2b2b2b][size=11][i]log(x, base)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["pow", str(math.pow.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Exponentiation[/b][/color]\n[color=2b2b2b][size=11][i]pow(x, y)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["factorial", str(math.factorial.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Factorial[/b][/color]\n[color=2b2b2b][size=11][i]factorial(x)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["sqrt", str(math.sqrt.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Square Root[/b][/color]\n[color=2b2b2b][size=11][i]sqrt(x)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["ceil", str(math.ceil.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Round Up[/b][/color]\n[color=2b2b2b][size=11][i]ceil(x)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["floor", str(math.floor.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Round Down[/b][/color]\n[color=2b2b2b][size=11][i]floor(x)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                                FunctionBtnBox:
                                                    function: ["trunc", str(math.trunc.__doc__)]
                                                    FunctionBtn:
                                                        text: "[color=000000][b]Truncate[/b][/color]\n[color=2b2b2b][size=11][i]trunc(x)[/i][/size][/color]"
                                                        on_press: root.calc_btn_pressed("<function>"+self.parent.function[0])
                                                    FunctionBtnInfo:
                                                        on_press: root.popuper(self.parent.function[1], "Function: " + self.parent.function[0])

                                BoxLayout:
                                    size_hint_x: None
                                    width: 5
                                    canvas.before:
                                        Color:
                                            rgba: (0.95, 0.95, 0.95, 1)
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size

                                BoxLayout:
                                    orientation: "vertical"
                                    size_hint: (None, None)
                                    size: (255, 250)

                                    BoxLayout:
                                        id: ind_calc
                                        size_hint: (None, None)
                                        size: (255, 55)
                                        padding: 0, 0, 0, 5
                                        spacing: 5

                                        Popup:
                                            id: indicator_var_builder
                                            size_hint: (None, None)
                                            size: (470, 250)
                                            title: "Build and Add Indicator Variable"
                                            on_parent: if self.parent == ind_calc: ind_calc.remove_widget(self)

                                            BoxLayout:
                                                orientation: "vertical"

                                                Label:
                                                    color: (0, 0, 0, 1)
                                                    text: "By default, each Indicator Variable will be dynamically calculated based on current formula iteration (Region - Year).\nHowever, fixed Region and Year values could be used too."
                                                    italic: True
                                                    font_size: 13
                                                    text_size: (self.width-30, self.height)
                                                    halign: "left"
                                                    valign: "middle"
                                                    canvas.before:
                                                        Color:
                                                            rgba: (1, 1, 1, 1)
                                                        Rectangle:
                                                            pos: self.pos
                                                            size: self.size

                                                BoxLayout:
                                                    size_hint_y: None
                                                    height: 40
                                                    canvas.before:
                                                        Color:
                                                            rgba: (1, 1, 1, 1)
                                                        Rectangle:
                                                            pos: self.pos
                                                            size: self.size

                                                    BoxLayout:
                                                        id: iry_table
                                                        padding: 5, 5, 0, 5
                                                        spacing: 5

                                                    Label:
                                                        id: iry_preview
                                                        size_hint: (None, None)
                                                        size: (160, 60)
                                                        color: (0, 0, 0, 1)
                                                        text: "[color=000000][b]"+self.indicator+"[/b][/color][sub][color=ff0080]"+self.region+"[/color][color=0d88d2]"+self.year+"[/color][/sub]"
                                                        indicator: "IA"
                                                        region: "[Region]"
                                                        year: "[Year]"
                                                        font_size: 26
                                                        markup: True

                                                AnchorLayout:
                                                    size_hint_y: None
                                                    height: 35
                                                    anchor_x: 'right'
                                                    anchor_y: 'center'

                                                    BoxLayout:
                                                        size_hint: (None, None)
                                                        size: (indicator_var_builder.width - 310, 30)
                                                        orientation: "horizontal"
                                                        padding: (0, 5, 0, 0)
                                                        spacing: 10

                                                        Button:
                                                            text: "Add Var."
                                                            italic: True
                                                            font_size: 13
                                                            color: (0.1,0.1,0.1,1)
                                                            background_normal: './Sources/math_function_normal.png'
                                                            background_down: './Sources/region_groups_normal.png'
                                                            on_release:
                                                                root.calc_btn_pressed(iry_preview.text)
                                                                indicator_var_builder.dismiss()

                                                        Button:
                                                            text: "Cancel"
                                                            italic: True
                                                            font_size: 13
                                                            color: (0.1,0.1,0.1,1)
                                                            background_normal: './Sources/math_function_normal.png'
                                                            background_down: './Sources/region_groups_normal.png'
                                                            on_release: indicator_var_builder.dismiss()

                                        Button:
                                            id: ind_calc_btn
                                            size_hint: (None, None)
                                            size: (125, 50)
                                            background_normal: './Sources/indicator_calc_btn_normal.png'
                                            normal: './Sources/indicator_calc_btn_normal.png'
                                            background_down: './Sources/indicator_calc_btn_down.png'
                                            on_press:
                                                indicator_var_builder.__self__.open()
                                                iry_table.clear_widgets()
                                                root.init_indicator_var_iry()

                                    GridLayout:
                                        id: calculator
                                        size_hint: (None, None)
                                        size: (255, 195)
                                        rows: 5
                                        cols: 4
                                        spacing: 5

                                        Calc_Func_Btn:
                                            text: '('
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Func_Btn:
                                            text: ')'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Button:
                                            text: '<'
                                            color: (0, 0, 0, 0)
                                            background_normal: './Sources/c_calc_btn_normal.png'
                                            normal: './Sources/c_calc_btn_normal.png'
                                            background_down: './Sources/c_calc_btn_down.png'
                                            on_press: root.calc_backspace_pressed()

                                        Button:
                                            text: 'C'
                                            color: (0, 0, 0, 0)
                                            background_normal: './Sources/call_calc_btn_normal.png'
                                            normal: './Sources/call_calc_btn_normal.png'
                                            background_down: './Sources/call_calc_btn_down.png'
                                            on_press: root.clear_formula()

                                        Calc_Arith_Btn:
                                            text: '7'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '8'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '9'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Func_Btn:
                                            text: '/'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '4'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '5'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '6'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Func_Btn:
                                            text: '*'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '1'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '2'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '3'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Func_Btn:
                                            text: '-'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '0'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Calc_Arith_Btn:
                                            text: '.'
                                            on_press: root.calc_btn_pressed(self.text)

                                        Saver:
                                            caller: root.exec_formula
                                            text: 'EXEC'
                                            size_hint: (None, None)
                                            size: (60, 35)
                                            background_normal: './Sources/exec_calc_btn_normal.png'
                                            normal: './Sources/exec_calc_btn_normal.png'
                                            background_down: './Sources/exec_calc_btn_down.png'
                                            color: (1, 1, 1, 1) if self.state == 'normal' else (0, 0, 0, 1)
                                            on_press:
                                                if len(my_formula.children)>1: self.show_save("Files: my_index.csv, my_index.log")
                                                else: root.popuper("Empty formula..", "Warning!")

                                        Calc_Func_Btn:
                                            text: '+'
                                            on_press: root.calc_btn_pressed(self.text)

                            GridLayout:
                                cols: 2
                                spacing: (0, 4)

                                BoxLayout:
                                    size_hint_x: None
                                    width: 3

                                Label:
                                    size_hint_y: None
                                    height: 20
                                    font_size: 16
                                    bold: True
                                    text_size: (self.width-10, self.height-5)
                                    halign: "left"
                                    valign: "bottom"
                                    text: "Hint.."
                                    color: (0.3, 0.3, 0.3, 1)

                                FormulaHintItem:
                                FormulaHintLabel:
                                    text: '[color=f54236][b]Iterations:[/b][/color] [color=666666]This formula will be calculated for each selected Region and Year in "Series Selection". (Num of Iterations = Regions x Years)[/color]'
                                    height: 65

                                FormulaHintItem:
                                FormulaHintLabel:
                                    text: "[color=f54236][b]Functions:[/b][/color] [color=666666]All functions must return a number. If a function takes more than one parameters, use comma to separate them.[/color]"
                                    height: 65

                                FormulaHintItem:
                                FormulaHintLabel:
                                    text: '[color=f54236][b]Saving:[/b][/color] [color=666666]You must first select the location where results (my_index.csv) and log (my_index.log) will be stored.[/color]'
                                    height: 50

                                FormulaHintItem:
                                FormulaHintLabel:
                                    text: '[color=f54236][b]Validation:[/b][/color] [color=666666]Check log file for any syntax errors, or missing indicator values.[/color]'
                                    height: 50


<WorldMapSVG>:
    size_hint: (None, None)
    size: (6200, 2700)
    do_rotation: False
    scale: 0.2
    scale_min: 0.2
    scale_max: 1

    FloatLayout:

        Image:
            opacity: 1 if root.show_labels else 0
            size_hint: (None, None)
            pos_hint: (None, None)
            pos: (-334, -816)
            size: self.texture_size
            source: './Sources/RegionLabels.png'
            allow_stretch: True

        FloatLayout:
            opacity: 1 if root.show_borders else 0

            Image:
                opacity: 1 if root.scale > 0.4 else 0
                size_hint: (None, None)
                pos_hint: (None, None)
                pos: (-334, -816)
                size: self.texture_size
                source: './Sources/RegionBorders_S.png'
                allow_stretch: True

            Image:
                opacity: 1 if root.scale < 0.4 else 0
                size_hint: (None, None)
                pos_hint: (None, None)
                pos: (-334, -816)
                size: self.texture_size
                source: './Sources/RegionBorders_L.png'
                allow_stretch: True

<MapDesigner>:
    map_canvas: map_canvas
    th_years_stack: th_years_stack
    th_data_table_regions: th_data_table_regions
    th_data_table_values: th_data_table_values
    start_color: start_color.__self__
    end_color: end_color.__self__
    legend: legend

    borders_switch: borders_switch
    labels_switch: labels_switch

    name: 'MapDesignerScreen'

    FloatLayout:
        orientation: "vertical"
        size_hint_x: None
        width: root.width - 1

        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            height: root.height - 120

            XLine:

            BoxLayout:
                id: th_main_frame
                canvas.before:
                    Color:
                        rgba: (0, 0, 0, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                SvgWidget:
                    id: map_canvas
                    canvas.before:
                        Color:
                            rgba: (0.76, 0.83, 0.88, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                RelativeLayout:
                    id: rl
                    size_hint: None, None
                    width: 0 if th_main_frame.height < 150 else thematic_toolbox.width
                    height: 150 if th_main_frame.height < 150 else th_main_frame.height

                    Splitter:
                        id: thematic_toolbox
                        size_hint_x: None
                        width: 13
                        sizable_from: 'left'
                        min_size: 13
                        max_size: 311
                        canvas.before:
                            Color:
                                rgba: (1, 1, 1, 1)
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        BoxLayout:
                            size_hint_x: None
                            width: 298

                            Accordion:
                                orientation: 'vertical'
                                min_space: 48

                                AccordionItem:
                                    min_space: 48
                                    background_normal: './Sources/button_hovered.png'
                                    background_selected: './Sources/button_down.png'
                                    title: 'Legend'

                                    BoxLayout:
                                        opacity: 1 if th_data_table_values.children else 0
                                        orientation: "vertical"
                                        padding: (20,6,20,6)

                                        ScrollView:
                                            bar_width: 2
                                            bar_margin: 2
                                            bar_inactive_color: (1, 1, 1, 1)
                                            bar_color: (0.32, 0.17, 0.22, 1)
                                            do_scroll_x: False

                                            GridLayout:
                                                id: legend
                                                padding: (6,6,6,6)
                                                spacing: 10
                                                cols: 1
                                                size_hint_y:None
                                                height: self.minimum_height

                                        XLine:

                                        BoxLayout:
                                            orientation: "vertical"
                                            size_hint_y: None
                                            height: 90

                                            Label:
                                                size_hint_y: None
                                                height: 20
                                                text: "Thematic Design"
                                                bold: True
                                                color: (0, 0, 0, 1)
                                                font_size: 13
                                                text_size: (self.width, self.height)
                                                halign: "center"
                                                valign: "bottom"

                                            BoxLayout:
                                                id: clr_classify
                                                size_hint_y: None
                                                height: 50
                                                canvas.before:
                                                    Color:
                                                        rgba: (0.9, 0.9, 0.9, 1)
                                                    Rectangle:
                                                        pos: self.pos
                                                        size: self.size

                                                Popup:
                                                    id: cp_start_color
                                                    title: 'Color Select'
                                                    size_hint: None, None
                                                    size: 400,500
                                                    on_parent:
                                                        if self.parent == clr_classify: self.parent.remove_widget(self)

                                                    ColorPicker:
                                                        id: start_color

                                                Popup:
                                                    id: cp_end_color
                                                    title: 'Color Select'
                                                    size_hint: None, None
                                                    size: 400,500
                                                    on_parent:
                                                        if self.parent == clr_classify: self.parent.remove_widget(self)

                                                    ColorPicker:
                                                        id: end_color

                                                BoxLayout:
                                                    orientation: "vertical"

                                                    BoxLayout:
                                                        padding: 10,0,10,0
                                                        spacing: 5

                                                        BoxLayout:
                                                            size_hint: (None, None)
                                                            size: (52,27)
                                                            padding: 1
                                                            canvas.before:
                                                                Color:
                                                                    rgba: (0, 0, 0, 1)
                                                                Rectangle:
                                                                    pos: self.pos
                                                                    size: self.size

                                                            Button:
                                                                size_hint: None, None
                                                                size: (50,25)
                                                                text: "FROM"
                                                                font_size: 11
                                                                italic: True
                                                                color: (0,0,0,1)
                                                                background_normal: './Sources/transparent_frame.png'
                                                                background_down: './Sources/transparent_frame.png'
                                                                canvas.before:
                                                                    Color:
                                                                        rgba: start_color.color
                                                                    Rectangle:
                                                                        pos: self.pos
                                                                        size: self.size
                                                                on_press: cp_start_color.open()

                                                        BoxLayout:
                                                            size_hint: (None, None)
                                                            size: (52,27)
                                                            padding: 1
                                                            canvas.before:
                                                                Color:
                                                                    rgba: (0, 0, 0, 1)
                                                                Rectangle:
                                                                    pos: self.pos
                                                                    size: self.size

                                                            Button:
                                                                size_hint: None, None
                                                                size: (50,25)
                                                                text: "TO"
                                                                font_size: 11
                                                                italic: True
                                                                color: (0,0,0,1)
                                                                border: 0,0,0,0
                                                                background_normal: './Sources/transparent_frame.png'
                                                                background_down: './Sources/transparent_frame.png'
                                                                canvas.before:
                                                                    Color:
                                                                        rgba: end_color.color
                                                                    Rectangle:
                                                                        pos: self.pos
                                                                        size: self.size
                                                                on_press: cp_end_color.open()

                                                    Label:
                                                        size_hint_y: None
                                                        height: 15
                                                        text: "Pick Range Colors"
                                                        color: (0,0,0,1)
                                                        italic: True
                                                        font_size: 11

                                                BoxLayout:

                                                    Label:
                                                        text_size: (self.width-20, self.height)
                                                        halign: "right"
                                                        valign: "middle"
                                                        text: "Equal\nIntervals"
                                                        color: (0,0,0,1)
                                                        italic: True
                                                        font_size: 11

                                                    BoxLayout:
                                                        size_hint_x: None
                                                        width: 10
                                                        orientation: "vertical"
                                                        padding: 0,15,0,15
                                                        spacing: 5
                                                        Button:
                                                            text: "+"
                                                            font_size: 18
                                                            color: (0,0,0,1)
                                                            background_normal: './Sources/transparent_frame.png'
                                                            background_down: './Sources/transparent_frame.png'
                                                            on_press: intervals.text = str((int(intervals.text) + 1))

                                                        Button:
                                                            text: "-"
                                                            font_size: 18
                                                            color: (0,0,0,1)
                                                            background_normal: './Sources/transparent_frame.png'
                                                            background_down: './Sources/transparent_frame.png'
                                                            on_press: intervals.text = str(max(1, (int(intervals.text) - 1)))

                                                    AnchorLayout:
                                                        anchor_x: 'center'
                                                        anchor_y: 'center'
                                                        size_hint_x: None
                                                        width: 30

                                                        Label:
                                                            id: intervals
                                                            size_hint: (None, None)
                                                            size: (30, 30)
                                                            text: "1"
                                                            font_size: 20
                                                            bold: True
                                                            color: (0,0,0,1)

                                            AnchorLayout:
                                                size_hint_y: None
                                                height: 20
                                                anchor_x: 'right'
                                                anchor_y: 'bottom'

                                                Button:
                                                    size_hint: (None, None)
                                                    size: (50, 19)
                                                    text: "Apply"
                                                    color: (1, 1, 1, 1)
                                                    font_size: 11
                                                    background_normal: './Sources/black.png'
                                                    on_release: root.calc_linear_gradient(start_color.hex_color[:-2], end_color.hex_color[:-2], int(intervals.text))

                                AccordionItem:
                                    min_space: 48
                                    background_normal: './Sources/button_hovered.png'
                                    background_selected: './Sources/button_down.png'
                                    title: 'Data Table'

                                    ScrollView:
                                        opacity: 1 if th_data_table_values.children else 0
                                        bar_width: 2
                                        bar_margin: 2
                                        bar_inactive_color: (1, 1, 1, 1)
                                        bar_color: (0.32, 0.17, 0.22, 1)
                                        do_scroll_x: False

                                        GridLayout:
                                            padding: (6,6,6,6)
                                            cols: 1
                                            size_hint_y:None
                                            height: self.minimum_height

                                            BoxLayout:
                                                size_hint_y: None
                                                height: 20
                                                canvas.before:
                                                    Color:
                                                        rgba: (0, 0, 0, 1)
                                                    Rectangle:
                                                        pos: self.pos
                                                        size: self.size

                                                Label:
                                                    size_hint: (None, None)
                                                    width: 198
                                                    text: "Region"
                                                    text_size: (self.width, self.height)
                                                    halign: "center"
                                                    valign: "middle"
                                                    height: 20
                                                    color: (1, 1, 1, 1)
                                                    font_size: 13
                                                    bold: True

                                                BoxLayout:
                                                    size_hint: (None, None)
                                                    size: (84, 20)

                                                    Label:
                                                        size_hint: (None, None)
                                                        width: 54
                                                        text: "Years"
                                                        text_size: (self.width, self.height)
                                                        halign: "right"
                                                        valign: "middle"
                                                        height: 20
                                                        color: (1, 1, 1, 1)
                                                        font_size: 13
                                                        bold: True

                                                    BoxLayout:
                                                        orientation: "vertical"
                                                        size_hint: (None, None)
                                                        size: (30, 20)
                                                        spacing: 4

                                                        Button:
                                                            size_hint: (None, None)
                                                            size: (30, 8)
                                                            border: (0, 0, 0, 0)
                                                            background_normal:'./Sources/ascending_down.png'
                                                            background_down:'./Sources/ascending_normal.png'
                                                            on_press: root.sort_data("ascending")

                                                        Button:
                                                            size_hint: (None, None)
                                                            size: (30, 8)
                                                            border: (0, 0, 0, 0)
                                                            background_normal: './Sources/descending_down.png'
                                                            background_down: './Sources/descending_normal.png'
                                                            on_press: root.sort_data("descending")

                                            BoxLayout:
                                                size_hint_y: None
                                                # 12 = 2 self paddings
                                                height: th_data_table_regions.minimum_height
                                                spacing: 1
                                                canvas.before:
                                                    Color:
                                                        rgba: (0, 0, 0, 1)
                                                    Rectangle:
                                                        pos: self.pos
                                                        size: self.size

                                                GridLayout:
                                                    id: th_data_table_regions
                                                    size_hint_x: None
                                                    padding: (1,0,0,1)
                                                    spacing: 1
                                                    width: 200
                                                    cols: 1
                                                    canvas.before:
                                                        Color:
                                                            rgba: (0, 0, 0, 1)
                                                        Rectangle:
                                                            pos: self.pos
                                                            size: self.size

                                                GridLayout:
                                                    id: th_data_table_values
                                                    size_hint_x: None
                                                    padding: 0,0,1,1
                                                    spacing: 1
                                                    width: 84
                                                    cols: 1
                                                    canvas.before:
                                                        Color:
                                                            rgba: (0, 0, 0, 1)
                                                        Rectangle:
                                                            pos: self.pos
                                                            size: self.size

            XLine:

            BoxLayout:
                size_hint_y: None
                height: 35
                canvas.before:
                    Color:
                        rgba: (0.22, 0.22, 0.22, 1)
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Label:
                    size_hint_x: None
                    height: 50
                    font_size: 13
                    text: "Year Selected:"
                    color: (1,1,1,1)
                    italic: True

                BoxLayout:
                    padding: 3

                    ScrollView:
                        bar_width: 1
                        bar_margin: 3
                        bar_inactive_color: (0.22, 0.22, 0.22, 1)
                        bar_color: (0.95, 0.95, 0.95, 1)
                        do_scroll_y: False

                        GridLayout:
                            id: th_years_stack
                            rows: 1
                            size_hint: (None, None)
                            size: (self.minimum_width, self.minimum_height)
                            padding: 5,4,5,0
                            spacing: 2

        BoxLayout:
            size_hint_y: None
            height: 120
            pos: 0, root.height - 120
            canvas.before:
                Color:
                    rgba: (1, 1, 1, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: "vertical"

                BoxLayout:
                    Image:
                        size_hint: None, None
                        size: 415, 100
                        source: './Sources/zoom_move.png'
                        allow_stretch: False

                BoxLayout:
                    size_hint: None, None
                    size: 415, 20

                    Label:
                        size_hint: None, None
                        size: 118, 20
                        text: "Move"
                        color: (0,0,0,1)
                        font_size: 12

                    Label:
                        size_hint: None, None
                        size: 297, 20
                        text: "Zoom"
                        color: (0,0,0,1)
                        font_size: 12

            AnchorLayout:
                anchor_x: 'right'
                anchor_y: 'center'
                size_hint_x: None
                width: 300
                padding: 10,10,10,10

                BoxLayout:
                    size_hint_x: None
                    width: 280 if thematic_toolbox.width < 20 else 200
                    canvas.before:
                        Color:
                            rgba: (0.18, 0.18, 0.18, 1)
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    BoxLayout:
                        size_hint_x: None
                        width: 100
                        padding: 10
                        orientation: "vertical"

                        Label:
                            size_hint_y: None
                            height: 18
                            text: "Export Map:"
                            font_size: 12

                        BoxLayout:
                            size_hint: None, None
                            size: 80, 35
                            padding: 5,0,5,0
                            spacing: 6

                            Saver:
                                cnv: th_main_frame
                                size_hint: None, None
                                size: 32, 32
                                background_normal: './Sources/save_to_png_normal.png'
                                background_down: './Sources/save_to_png_down.png'
                                background_disabled_down: './Sources/save_to_png_disabled.png'
                                background_disabled_normal: './Sources/save_to_png_disabled.png'
                                disabled: not map_canvas.children
                                on_release: self.show_save("File: TH_Map.png")

                            Saver:
                                size_hint: None, None
                                size: 32, 32
                                background_normal: './Sources/save_to_svg_normal.png'
                                background_down: './Sources/save_to_svg_down.png'
                                background_disabled_down: './Sources/save_to_svg_disabled.png'
                                background_disabled_normal: './Sources/save_to_svg_disabled.png'
                                disabled: not map_canvas.children
                                on_release: self.show_save("File: TH_Map.svg")

                    BoxLayout:
                        orientation: "vertical"
                        size_hint_x: None
                        width: 100
                        padding: (0,5,0,5)
                        spacing: 2

                        BoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: 45

                            Label:
                                size_hint_y: None
                                height: 14
                                text: "Borders"
                                font_size: 12

                            Switch:
                                id: borders_switch
                                size_hint_y: None
                                height: 30
                                disabled: not map_canvas.children
                                active: True
                                on_active: map_canvas.children[0].show_borders = self.active

                        BoxLayout:
                            orientation: "vertical"
                            size_hint_y: None
                            height: 45

                            Label:
                                size_hint_y: None
                                height: 14
                                text: "Labels"
                                font_size: 12

                            Switch:
                                id: labels_switch
                                size_hint_y: None
                                height: 30
                                disabled: not map_canvas.children
                                active: True
                                on_active: map_canvas.children[0].show_labels = self.active

                    BoxLayout:
                        orientation: "vertical"
                        size_hint_x: None
                        width: 80 if thematic_toolbox.width < 20 else 0
                        opacity: 1 if thematic_toolbox.width < 20 else 0

                        Label:
                            size_hint: None, None
                            size: 80, 45
                            text: "Data Viewer &\nMap Creator"
                            font_size: 11
                            bold: True
                            italic: True
                            text_size: (self.width, self.height)
                            halign: "center"
                            valign: "middle"

                        Image:
                            size_hint: None, None
                            size: 80, 55
                            source: './Sources/slider_arrow.png'
                            allow_stretch: False
