#File name: (hint of file name).py
#:kivy 1.9.0
#Δεν χρειάζεται να χρησιμοποιούντε όλες οι παρακάτω class

<Layout>
    Button:
        color: 0,1,0,1
        text: "1"
        pos_hint: {"top": 1, "bottom": 1}

    Button:
        pos_hint: {"right": 0.5, "left": 0.5}
        color: 1,0,0,1
        text: "2"

    Button:
        color: 0,1,0,1
        text: "3"
        pos_hint: {"x": 1, "y": 1}

<Button>
    font_size: 40
    size_hint: 0.3, 0.2